// src/utils/locations.ts
// Country → State → City data for the checkout address dropdowns.
// Cities are the major ones per state; checkout offers an "Other" fallback for the rest.

export interface CountryOption {
  code:   string;
  name:   string;
  states: Record<string, string[]>;
}

export const COUNTRIES: CountryOption[] = [
  {
    code: 'IN',
    name: 'India',
    states: {
      'Andaman and Nicobar Islands': ['Port Blair'],
      'Andhra Pradesh': ['Guntur', 'Kakinada', 'Kurnool', 'Nellore', 'Rajahmundry', 'Tirupati', 'Vijayawada', 'Visakhapatnam'],
      'Arunachal Pradesh': ['Itanagar', 'Naharlagun', 'Pasighat', 'Tawang'],
      'Assam': ['Dibrugarh', 'Guwahati', 'Jorhat', 'Nagaon', 'Silchar', 'Tezpur'],
      'Bihar': ['Bhagalpur', 'Darbhanga', 'Gaya', 'Muzaffarpur', 'Patna', 'Purnia'],
      'Chandigarh': ['Chandigarh'],
      'Chhattisgarh': ['Bhilai', 'Bilaspur', 'Durg', 'Korba', 'Raipur'],
      'Dadra and Nagar Haveli and Daman and Diu': ['Daman', 'Diu', 'Silvassa'],
      'Delhi': ['Delhi', 'New Delhi'],
      'Goa': ['Mapusa', 'Margao', 'Panaji', 'Ponda', 'Vasco da Gama'],
      'Gujarat': ['Ahmedabad', 'Bhavnagar', 'Gandhinagar', 'Jamnagar', 'Junagadh', 'Rajkot', 'Surat', 'Vadodara'],
      'Haryana': ['Ambala', 'Faridabad', 'Gurugram', 'Hisar', 'Karnal', 'Panipat', 'Rohtak', 'Sonipat'],
      'Himachal Pradesh': ['Dharamshala', 'Kullu', 'Mandi', 'Manali', 'Shimla', 'Solan'],
      'Jammu and Kashmir': ['Anantnag', 'Baramulla', 'Jammu', 'Srinagar'],
      'Jharkhand': ['Bokaro', 'Deoghar', 'Dhanbad', 'Hazaribagh', 'Jamshedpur', 'Ranchi'],
      'Karnataka': ['Belagavi', 'Bengaluru', 'Davanagere', 'Dharwad', 'Hubballi', 'Kalaburagi', 'Mangaluru', 'Mysuru', 'Udupi'],
      'Kerala': ['Alappuzha', 'Kannur', 'Kochi', 'Kollam', 'Kozhikode', 'Palakkad', 'Thiruvananthapuram', 'Thrissur'],
      'Ladakh': ['Kargil', 'Leh'],
      'Lakshadweep': ['Kavaratti'],
      'Madhya Pradesh': ['Bhopal', 'Gwalior', 'Indore', 'Jabalpur', 'Rewa', 'Sagar', 'Ujjain'],
      'Maharashtra': ['Amravati', 'Aurangabad', 'Kolhapur', 'Mumbai', 'Nagpur', 'Nashik', 'Navi Mumbai', 'Pune', 'Solapur', 'Thane'],
      'Manipur': ['Churachandpur', 'Imphal', 'Thoubal'],
      'Meghalaya': ['Jowai', 'Shillong', 'Tura'],
      'Mizoram': ['Aizawl', 'Champhai', 'Lunglei'],
      'Nagaland': ['Dimapur', 'Kohima', 'Mokokchung'],
      'Odisha': ['Berhampur', 'Bhubaneswar', 'Cuttack', 'Puri', 'Rourkela', 'Sambalpur'],
      'Puducherry': ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
      'Punjab': ['Amritsar', 'Bathinda', 'Jalandhar', 'Ludhiana', 'Mohali', 'Patiala'],
      'Rajasthan': ['Ajmer', 'Alwar', 'Bhilwara', 'Bikaner', 'Jaipur', 'Jodhpur', 'Kota', 'Udaipur'],
      'Sikkim': ['Gangtok', 'Gyalshing', 'Namchi'],
      'Tamil Nadu': ['Chennai', 'Coimbatore', 'Erode', 'Madurai', 'Salem', 'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli', 'Vellore'],
      'Telangana': ['Hyderabad', 'Karimnagar', 'Khammam', 'Nizamabad', 'Secunderabad', 'Warangal'],
      'Tripura': ['Agartala', 'Dharmanagar', 'Udaipur'],
      'Uttar Pradesh': ['Agra', 'Aligarh', 'Bareilly', 'Ghaziabad', 'Gorakhpur', 'Kanpur', 'Lucknow', 'Meerut', 'Noida', 'Prayagraj', 'Varanasi'],
      'Uttarakhand': ['Dehradun', 'Haldwani', 'Haridwar', 'Nainital', 'Rishikesh', 'Roorkee'],
      'West Bengal': ['Asansol', 'Baharampur', 'Bally', 'Ballygunge', 'Bankura', 'Bardhaman', 'Barasat', 'Barrackpore', 'Berhampore', 'Bhatpara', 'Bishnupur', 'Bolpur', 'Bongaon', 'Chandannagar', 'Cooch Behar', 'Darjeeling', 'Durgapur', 'English Bazar', 'Haldia', 'Howrah', 'Jalpaiguri', 'Jhargram', 'Kalyani', 'Kamarhati', 'Kanchrapara', 'Kharagpur', 'Kolkata', 'Krishnanagar', 'Malda', 'Midnapore', 'Nabadwip', 'New Barrackpore', 'North Dumdum', 'Purulia', 'Raiganj', 'Rajpur Sonarpur', 'Ranaghat', 'Sainthia', 'Santipur', 'Serampore', 'Shantiniketan', 'Siliguri', 'Suri', 'Tamluk', 'Uttarpara'],
    },
  },
  {
    code: 'US',
    name: 'United States',
    states: {
      'Alabama':        ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile'],
      'Alaska':         ['Anchorage', 'Fairbanks', 'Juneau'],
      'Arizona':        ['Phoenix', 'Tucson', 'Mesa', 'Scottsdale', 'Tempe', 'Flagstaff'],
      'Arkansas':       ['Little Rock', 'Fayetteville', 'Fort Smith'],
      'California':     ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Sacramento', 'Fresno', 'Oakland', 'Long Beach'],
      'Colorado':       ['Denver', 'Colorado Springs', 'Aurora', 'Boulder', 'Fort Collins'],
      'Connecticut':    ['Hartford', 'New Haven', 'Stamford', 'Bridgeport'],
      'Delaware':       ['Wilmington', 'Dover', 'Newark'],
      'District of Columbia': ['Washington'],
      'Florida':        ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Tallahassee', 'Fort Lauderdale'],
      'Georgia':        ['Atlanta', 'Savannah', 'Augusta', 'Athens', 'Columbus'],
      'Hawaii':         ['Honolulu', 'Hilo', 'Kailua'],
      'Idaho':          ['Boise', 'Idaho Falls', 'Pocatello'],
      'Illinois':       ['Chicago', 'Springfield', 'Naperville', 'Peoria', 'Rockford'],
      'Indiana':        ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend'],
      'Iowa':           ['Des Moines', 'Cedar Rapids', 'Davenport', 'Iowa City'],
      'Kansas':         ['Wichita', 'Overland Park', 'Kansas City', 'Topeka'],
      'Kentucky':       ['Louisville', 'Lexington', 'Frankfort', 'Bowling Green'],
      'Louisiana':      ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette'],
      'Maine':          ['Portland', 'Augusta', 'Bangor'],
      'Maryland':       ['Baltimore', 'Annapolis', 'Rockville', 'Frederick'],
      'Massachusetts':  ['Boston', 'Worcester', 'Springfield', 'Cambridge'],
      'Michigan':       ['Detroit', 'Grand Rapids', 'Lansing', 'Ann Arbor'],
      'Minnesota':      ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth'],
      'Mississippi':    ['Jackson', 'Gulfport', 'Biloxi'],
      'Missouri':       ['Kansas City', 'St. Louis', 'Springfield', 'Columbia'],
      'Montana':        ['Billings', 'Missoula', 'Helena', 'Bozeman'],
      'Nebraska':       ['Omaha', 'Lincoln'],
      'Nevada':         ['Las Vegas', 'Reno', 'Henderson', 'Carson City'],
      'New Hampshire':  ['Manchester', 'Nashua', 'Concord'],
      'New Jersey':     ['Newark', 'Jersey City', 'Paterson', 'Trenton'],
      'New Mexico':     ['Albuquerque', 'Santa Fe', 'Las Cruces'],
      'New York':       ['New York City', 'Buffalo', 'Rochester', 'Albany', 'Syracuse'],
      'North Carolina': ['Charlotte', 'Raleigh', 'Durham', 'Greensboro', 'Asheville'],
      'North Dakota':   ['Fargo', 'Bismarck', 'Grand Forks'],
      'Ohio':           ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Dayton'],
      'Oklahoma':       ['Oklahoma City', 'Tulsa', 'Norman'],
      'Oregon':         ['Portland', 'Salem', 'Eugene', 'Bend'],
      'Pennsylvania':   ['Philadelphia', 'Pittsburgh', 'Harrisburg', 'Allentown'],
      'Rhode Island':   ['Providence', 'Warwick', 'Newport'],
      'South Carolina': ['Charleston', 'Columbia', 'Greenville'],
      'South Dakota':   ['Sioux Falls', 'Rapid City', 'Pierre'],
      'Tennessee':      ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga'],
      'Texas':          ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth', 'El Paso'],
      'Utah':           ['Salt Lake City', 'Provo', 'Ogden', 'St. George'],
      'Vermont':        ['Burlington', 'Montpelier'],
      'Virginia':       ['Virginia Beach', 'Richmond', 'Norfolk', 'Arlington', 'Alexandria'],
      'Washington':     ['Seattle', 'Spokane', 'Tacoma', 'Olympia', 'Bellevue'],
      'West Virginia':  ['Charleston', 'Huntington', 'Morgantown'],
      'Wisconsin':      ['Milwaukee', 'Madison', 'Green Bay'],
      'Wyoming':        ['Cheyenne', 'Casper', 'Laramie'],
    },
  },
  {
    code: 'CA',
    name: 'Canada',
    states: {
      'Alberta':                   ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge'],
      'British Columbia':          ['Vancouver', 'Victoria', 'Surrey', 'Burnaby', 'Kelowna'],
      'Manitoba':                  ['Winnipeg', 'Brandon'],
      'New Brunswick':             ['Fredericton', 'Moncton', 'Saint John'],
      'Newfoundland and Labrador': ["St. John's", 'Corner Brook'],
      'Northwest Territories':     ['Yellowknife'],
      'Nova Scotia':               ['Halifax', 'Sydney'],
      'Nunavut':                   ['Iqaluit'],
      'Ontario':                   ['Toronto', 'Ottawa', 'Mississauga', 'Hamilton', 'London', 'Kitchener'],
      'Prince Edward Island':      ['Charlottetown', 'Summerside'],
      'Quebec':                    ['Montreal', 'Quebec City', 'Laval', 'Gatineau', 'Sherbrooke'],
      'Saskatchewan':              ['Saskatoon', 'Regina'],
      'Yukon':                     ['Whitehorse'],
    },
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    states: {
      'England':          ['London', 'Manchester', 'Birmingham', 'Liverpool', 'Leeds', 'Bristol', 'Sheffield', 'Newcastle upon Tyne', 'Nottingham', 'Oxford', 'Cambridge'],
      'Northern Ireland': ['Belfast', 'Derry', 'Lisburn', 'Newry'],
      'Scotland':         ['Edinburgh', 'Glasgow', 'Aberdeen', 'Dundee', 'Inverness'],
      'Wales':            ['Cardiff', 'Swansea', 'Newport', 'Wrexham'],
    },
  },
  {
    code: 'AU',
    name: 'Australia',
    states: {
      'Australian Capital Territory': ['Canberra'],
      'New South Wales':              ['Sydney', 'Newcastle', 'Wollongong', 'Central Coast'],
      'Northern Territory':           ['Darwin', 'Alice Springs'],
      'Queensland':                   ['Brisbane', 'Gold Coast', 'Sunshine Coast', 'Townsville', 'Cairns'],
      'South Australia':              ['Adelaide', 'Mount Gambier'],
      'Tasmania':                     ['Hobart', 'Launceston'],
      'Victoria':                     ['Melbourne', 'Geelong', 'Ballarat', 'Bendigo'],
      'Western Australia':            ['Perth', 'Fremantle', 'Bunbury'],
    },
  },
];

const byAlpha = (a: string, b: string) => a.localeCompare(b);

export const SORTED_COUNTRIES = [...COUNTRIES].sort((a, b) => byAlpha(a.name, b.name));

export const getCountry = (code: string) => COUNTRIES.find(c => c.code === code);
export const getStates  = (code: string) => Object.keys(getCountry(code)?.states ?? {}).sort(byAlpha);
export const getCities  = (code: string, state: string) => [...(getCountry(code)?.states[state] ?? [])].sort(byAlpha);
